repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.6
    hooks:
      # GitHub Actions runners have ruff installed, so we only need to format here.
      # - id: ruff-check
      #   args: [--fix]
      - id: ruff-format
